[tox]
envlist = py38, py39, py310, lint, typecheck
isolated_build = True

[testenv]
deps =
    pytest
    pytest-mock
    ipython
commands =
    pytest tests/ -v

[testenv:lint]
deps = flake8
commands =
    flake8 src/ tests/

[testenv:typecheck]
deps = mypy
commands =
    mypy src/nexusviewpro/